version: "3"
services:
  mongodb_dev:
    image: "mongo"
  expressapi:
    build: ./server
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - mongodb_dev
  expressweb:
    build: ./client
    ports:
      - "4300:80"
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/localhost.crt:/etc/nginx/ssl/localhost.crt
      - ./nginx/localhost.key:/etc/nginx/ssl/localhost.key
    links:
      - expressapi
      - expressweb