version: "3"
services:
  frontend-app:
    image: frontend-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - application-network
  backend-app:
    image: backend-app
    ports:
      - "5000:5000"
    networks:
      - application-network
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - application-network
    volumes:
      - mongo-data:/data/db
networks:
  application-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
